### ISSUE TITLE
Open up blocking origin XHR

### ISSUE THREAD

**Issue by eugeneross** [numieco/patriot-trading#13]
I was trying to deploy this and was getting blocking access from the origin
![screen shot 2017-04-29 at 6 24 57 pm](https://cloud.githubusercontent.com/assets/174520/25559494/2f01bd66-2d09-11e7-86ef-6b9ce7693345.png)

**Comment by dhanesh-kapadiya** [comment]
Done by adding server at 6bd195d5e6923e09d5c55e05004cfb4fe2c4e05b.
