### ISSUE TITLE
Take off blue underline on links

### ISSUE THREAD

**Issue by eugeneross** [numieco/patriot-trading#15]
These are in the footer, but scan elsewhere in the project for them. 
![screen shot 2017-05-05 at 3 38 48 pm](https://cloud.githubusercontent.com/assets/174520/25761496/fd000e54-31a8-11e7-8ee4-822026db1b6f.png)

**Comment by dhanesh-kapadiya** [comment]
Done 703c7528889862b88df90519fdcbe5720d507d52.
