### ISSUE TITLE
Shrink font size for mobile sidebar

### ISSUE THREAD

**Issue by eugeneross** [numieco/patriot-trading#16]
Shrink the size of the font for the Links section on mobile. 16px should do the trick. This was taken on an iPhone 4. Should all be in one line. 
![screen shot 2017-05-05 at 3 40 02 pm](https://cloud.githubusercontent.com/assets/174520/25761574/3fdf5d06-31a9-11e7-8ad3-b2d9773c4a0a.png)

**Comment by dhanesh-kapadiya** [comment]
Fixed here 7d5ffce4f203dd80734fcc48b913805c449136b0
