### ISSUE TITLE
iPhone 7+ shows tablet layout 

### ISSUE THREAD

**Issue by eugeneross** [numieco/patriot-trading#17]
This only applies to the "Relevant News" links on iPhone 7+. It shows the tablet layout when it shouldn't. 
![screen shot 2017-05-05 at 3 43 11 pm](https://cloud.githubusercontent.com/assets/174520/25761660/92be3e02-31a9-11e7-9d3f-c9a2d0e039c4.png)

**Comment by dhanesh-kapadiya** [comment]
Done 3ec6a0f8c1c8c51dec9f9945f18a4475a66890ab.
