### ISSUE TITLE
Phone number styling

### ISSUE THREAD

**Issue by eugeneross** [numieco/patriot-trading#18]
Please find all instances of the phone number for the company and follow the styling I've set for it in the sidebar. 
![screen shot 2017-05-05 at 3 45 11 pm](https://cloud.githubusercontent.com/assets/174520/25761729/dabd2632-31a9-11e7-9a98-2a50e4018ac1.png)

**Comment by dhanesh-kapadiya** [comment]
Done in this commit 703c7528889862b88df90519fdcbe5720d507d52.
