### ISSUE TITLE
Adjust mobile menus

### ISSUE THREAD

**Issue by eugeneross** [numieco/patriot-trading#20]
These are acting weird for different screen sizes. A couple things I want to fix:

- take off blue underline for links
- on iPhone 6 bring the line of text and buttons up, not sure why it's at the bottom
- on iPhone 5 and iPhone 4 shrink the font size by four pixels
- on iPhone 5 and iPhone 4 replace the follow buttons for just the circles.
    - So below the line or text, there should be a facebook-blue circle button with a white Facebook logo and a twitter-blue circle button with a white twitter logo. You can adjust these values in code because they are SVGs.

I will provide design specs for this when I get back.

**Comment by eugeneross** [comment]
Screen Shot 2017-05-10 at 11.49.05 AM

**Comment by eugeneross** [comment]
I see that you removed the icons on the last commit. Please remove the rectangle buttons in favor for just the circles as depicted in the image above.

**Comment by dhanesh-kapadiya** [comment]
Done fac1b4135404abce66ef163957e5c1767d6b2241.
