### ISSUE TITLE
Use `:after` property for dashes

### ISSUE THREAD

**Issue by eugeneross** [numieco/patriot-trading#3]
To clean up the markup, use the pseudo `:after` when making the dashes. Ask me if you need guidance for this. 
<img width="254" alt="screen shot 2017-04-29 at 4 22 34 pm" src="https://cloud.githubusercontent.com/assets/174520/25558602/131e1a42-2cf8-11e7-939c-1683f5f919eb.png">

**Comment by dhanesh-kapadiya** [comment]
Done here 2f78545e2ff002f31a29230265330a2bfaed33f7.
