### ISSUE TITLE
Add border right to sidebar heading items

### ISSUE THREAD

**Issue by eugeneross** [numieco/patriot-trading#31]
Add a border to the right for all heading items. 

<img width="467" alt="screen shot 2017-05-16 at 7 24 29 pm" src="https://cloud.githubusercontent.com/assets/174520/26135877/501fdd0e-3a6d-11e7-80eb-cc917927c137.png">

**Comment by dhanesh-kapadiya** [comment]
Done 0469d26ae72e27817602cb29d2e1d42554149804.
