### ISSUE TITLE
Make SALE component maintain its horizontal position

### ISSUE THREAD

**Issue by eugeneross** [numieco/patriot-trading#32]
Is this possible? 

No matter what the browser width for desktop, make the sale component keep its same horizontal positioning while being fixed. See the images below.

![screen shot 2017-05-16 at 3 11 19 pm](https://cloud.githubusercontent.com/assets/174520/26135928/a623e0ec-3a6d-11e7-89e4-32c18e4c9424.png)

Normal, good position^

![screen shot 2017-05-16 at 3 11 23 pm](https://cloud.githubusercontent.com/assets/174520/26135934/affa98cc-3a6d-11e7-8c17-6c542f959dad.png)

Fixed position in the corner of the browser. 

Let me know if you have questions.

**Comment by dhanesh-kapadiya** [comment]
done 263fcede1c4a7e275175c317f6005d443c21c69d.
