### ISSUE TITLE
On Desktop, display all archives by default, no click

### ISSUE THREAD

**Issue by eugeneross** [numieco/patriot-trading#33]
Look at the GIF below. For desktop, this should show the archives that we have, much like how you had it before. This area shouldn't be clickable.

![bug](https://cloud.githubusercontent.com/assets/174520/26135992/174ba534-3a6e-11e7-9d50-9aa65e567e2f.gif)

**Comment by dhanesh-kapadiya** [comment]
Fixed here 0adb084.
