### ISSUE TITLE
Create headings

### ISSUE THREAD

**Issue by eugeneross** [numieco/patriot-trading#35]
Assign these three different types of font sizes to headings. We need H1, H2, and H3 so that we can style the static pages accordingly. I would create a section of styles for typography and then reflect the use of the new heading tags in the markup. See image below for reference. 
<img width="668" alt="screen shot 2017-05-18 at 3 28 29 pm" src="https://cloud.githubusercontent.com/assets/174520/26226073/1411d628-3bdf-11e7-9d74-4715e34252e4.png">

**Comment by dhanesh-kapadiya** [comment]
Done 1e1f53f9e5453c1fc3de4c3f89f2b449b9e02e44.
