### ISSUE TITLE
Link static pages to content

### ISSUE THREAD

**Issue by eugeneross** [numieco/patriot-trading#36]
List of static pages that will have content:

- About : `/about`
- Contact : `/contact`
- Faq : `/faq`
- Links: `/links`
- Live Radio : `/live-radio`
- Privacy Policy : `/privacy-policy`
- Terms of Service : `/terms-of-service`

For each page, in the content area, put an `H1` with the the title of the page so that I can enter the static content and style them.

**Comment by dhanesh-kapadiya** [comment]
Done d84de8ad72b91816cb1b97bcd27809e09559107e.
