### ISSUE TITLE
Change layout of posts with links

### ISSUE THREAD

**Issue by eugeneross** [numieco/patriot-trading#37]
See the attached image and Zeplin screen. Putting images on top of the title, and the link to the left of the title. Notice how the title lines up with the container, but the link icon doesn't. Use the `:before` pseudo to achieve this result. 

![desktop](https://cloud.githubusercontent.com/assets/174520/26226246/21332c02-3be0-11e7-8957-b234164b2e50.png)

**Comment by dhanesh-kapadiya** [comment]
Done 91b45ad010a06f45d5572c84b91c175a8728ea08.
