### ISSUE TITLE
Correct Archives page layout

### ISSUE THREAD

**Issue by eugeneross** [numieco/patriot-trading#38]
This is the correct way the archives page should look. Note the added heading at the top. This will be in Zeplin for reference as well.

![archives](https://cloud.githubusercontent.com/assets/174520/26226586/cb30418a-3be1-11e7-8fcf-adf483ae5aec.png)

**Comment by dhanesh-kapadiya** [comment]
Done 1a0a4edb9db22815841ae65e15ff5ed22ff0f534.
