### ISSUE TITLE
Excerpts for post links are cut off on all devices

### ISSUE THREAD

**Issue by eugeneross** [numieco/patriot-trading#4]
I've seen this on all devices, seems to be cut off and only shows half of a line of text. 
<img width="889" alt="screen shot 2017-04-29 at 4 16 18 pm" src="https://cloud.githubusercontent.com/assets/174520/25558607/351022bc-2cf8-11e7-978b-cd6d2da6dc62.png">

**Comment by dhanesh-kapadiya** [comment]
Done bc34da95c141c014d662e6dfbbb8708e40cde2ed.
