### ISSUE TITLE
Vertically center hamburger menu

### ISSUE THREAD

**Issue by eugeneross** [numieco/patriot-trading#41]
I adjusted the hamburger menu, but need to vertically center it within the header.

![screen shot 2017-05-18 at 4 01 46 pm](https://cloud.githubusercontent.com/assets/174520/26226910/f90ab8d6-3be3-11e7-88e0-affc4a421ec1.png)

**Comment by dhanesh-kapadiya** [comment]
done 428c5f69b7f17f562f191c0eece5607bd3cd35d2.
