### ISSUE TITLE
Blog page

### ISSUE THREAD

**Issue by eugeneross** [numieco/patriot-trading#43]
This is the blog page. It **only** contains written posts. Look at the image and Zeplin for reference. 

![blog](https://cloud.githubusercontent.com/assets/174520/26227491/bfa2b946-3be7-11e7-83dc-da6d625e0b2e.png)

**Comment by dhanesh-kapadiya** [comment]
Done eb2c733e965d4e66b12ebe208f0eff578cb0a491.
