### ISSUE TITLE
Archive featured post not 100% width

### ISSUE THREAD

**Issue by eugeneross** [numieco/patriot-trading#47]
Only applies to archive pages. Featured image doesn't behave like other featured posts. The image does not span 100% browser width on tablet + mobile. See image below:
![screen shot 2017-05-24 at 3 40 01 pm](https://cloud.githubusercontent.com/assets/174520/26428557/43bed01c-4097-11e7-94ba-fcf5e535b24e.png)

**Comment by dhanesh-kapadiya** [comment]
Done 8bfdaae82ad187db4c58a44edc91dc56b8ffce1d.
