### ISSUE TITLE
Archive menu doesn't stay closed

### ISSUE THREAD

**Issue by eugeneross** [numieco/patriot-trading#48]
Archive menu doesn't stay closed if I navigate from one archive page to another (April -> May for example) See gif below:

![bug](https://cloud.githubusercontent.com/assets/174520/26428613/91504fb8-4097-11e7-86aa-b253c39c02d2.gif)

**Comment by dhanesh-kapadiya** [comment]
Done b2e3f61163acbb79642d5e7bfc3668ca340a6388.
