### ISSUE TITLE
add 404 route and page

### ISSUE THREAD

**Issue by eugeneross** [numieco/patriot-trading#52]
We need to add a 404 page for older users that may come from a link that doesn't exist anymore. Here is a screenshot of it below:

![desktop - 404](https://cloud.githubusercontent.com/assets/174520/26471612/298c5618-4157-11e7-856f-f101a41b5b48.png)
![tablet - 404](https://cloud.githubusercontent.com/assets/174520/26471626/3453c676-4157-11e7-8272-86df4595d070.png)

Please refer to the Zeplin screen for specs

**Comment by dhanesh-kapadiya** [comment]
Done c278a449e17988e7b54e93454e6ffb0423f65fab.
