### ISSUE TITLE
fix tablet + mobile sidebar spacing issue

### ISSUE THREAD

**Issue by eugeneross** [numieco/patriot-trading#55]
See the image. I took off the `h3` tags for the link elements and this occurred in the sidebar content. 
If we can get this back to normal that would be great. 

![screen shot 2017-05-27 at 3 22 19 pm](https://cloud.githubusercontent.com/assets/174520/26524691/763b3bc4-42f0-11e7-9893-bb7779dbc877.png)

Please pull down latest branch of fix-issues

**Comment by dhanesh-kapadiya** [comment]
Done 76f2b6f.
