### ISSUE TITLE
Update position for radio and social links

### ISSUE THREAD

**Issue by eugeneross** [numieco/patriot-trading#56]
have these reflected in the screenshots below:

![desktop](https://cloud.githubusercontent.com/assets/174520/26536765/2e5d7e5c-43ef-11e7-941d-85ac6f392766.png)
![mobile - expanded - iphone 4 5 copy](https://cloud.githubusercontent.com/assets/174520/26536788/3c3f785e-43ef-11e7-921b-d42fddcb9232.png)
![mobile](https://cloud.githubusercontent.com/assets/174520/26536789/3c3ff5ae-43ef-11e7-81d9-8afab4c5dde1.png)

specs are in zeplin

**Comment by dhanesh-kapadiya** [comment]
Done 32780fbb6f692af6e878652ca624ad91e773cd20 and e83eb0dbfd927de0a24a09f95f786d0637608a1c.
