### ISSUE TITLE
Fix FAQ on tablet/mobile screens

### ISSUE THREAD

**Issue by eugeneross** [numieco/patriot-trading#65]
see image below 
![screen shot 2017-06-02 at 3 02 37 pm](https://cloud.githubusercontent.com/assets/174520/26746539/13577b08-47a5-11e7-84d9-41d0a1ab16aa.png)

**Comment by dhanesh-kapadiya** [comment]
Done 561a5effac85cd95fa233fe0055fafe157065f33.
