### ISSUE TITLE
Fix footer logo for tablet and mobile screens

### ISSUE THREAD

**Issue by eugeneross** [numieco/patriot-trading#7]
The logo isn't acting properly on the footer on tablet and mobile screens. 

![screen shot 2017-04-29 at 4 30 36 pm](https://cloud.githubusercontent.com/assets/174520/25558659/30c9e246-2cf9-11e7-8c3a-1bb629a6c80f.png)

**Comment by dhanesh-kapadiya** [comment]
Done 265a2d73e875646f021bebd9604e2b5e1401e8bb.
