### ISSUE TITLE
Arrow for archives button is below text on mobile

### ISSUE THREAD

**Issue by eugeneross** [numieco/patriot-trading#8]
see image 
![screen shot 2017-04-29 at 4 31 25 pm](https://cloud.githubusercontent.com/assets/174520/25558669/6c17145e-2cf9-11e7-981b-9f8bd367fd5e.png)

**Comment by dhanesh-kapadiya** [comment]
Done d8751d52fdd0325612477415a39ebd129f8d0f6b.
